AllCops:
  Exclude:
    - db/**/*
    - bin/**/*
    - spec/support/**/*
    - vendor/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7.0

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

###################### Temporarily disabled ####################################

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

# To be re-enabled with Style/IfUnlessModifier
Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Documentation:
  Enabled: false





Style/GuardClause:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# To be re-enabled with Metrics/LineLength
Style/IfUnlessModifier:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false
